### ISSUE TITLE
There is something wrong

### ISSUE THREAD

**Issue by zysNLP** [baidu/Dialogue#24]
The line 10 in the document "test_and_evaluate.py" should be 

import utils.evaluation as eva  #for ubuntu
#import utils.douban_evaluation as eva  #for douban

not just "import utils.evaluation as eva"
I am not sure if the same line in the document "train_and_evaluate.py" should be modified or not.It seems to work without modification.

**Comment by xyzhou-puck** [comment]
assign this issue to @luluxing3 .

**Comment by luluxing3** [comment]
Hi zysNLP,
There is no need to make any modification in train_and_evaluate.py.

`import utils.douban_evaluation as eva #for douban` 
The modification in test_and_evaluation.py is due to the different evaluation for douban corpus.
The test set of douban corpus may have multiple positive responses and add two metrics(MAP, MRR) to evaluate the rank performance, comparing with ubuntu corpus.
While there is no difference in training.

**Comment by zysNLP** [comment]
Ok! Thank you very much!
